# generated by datamodel-codegen:
#   filename:  rotunda-profile.openapi.yaml

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class DoNotTrack(Enum):
    field_0 = '0'
    field_1 = '1'
    unspecified = 'unspecified'


class NavigatorProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_agent: str | None = Field(None, alias='userAgent')
    do_not_track: DoNotTrack | None = Field(None, alias='doNotTrack')
    app_code_name: str | None = Field(None, alias='appCodeName')
    app_name: str | None = Field(None, alias='appName')
    app_version: str | None = Field(None, alias='appVersion')
    oscpu: str | None = None
    language: str | None = None
    languages: list[str] | None = None
    platform: str | None = None
    hardware_concurrency: int | None = Field(None, alias='hardwareConcurrency', ge=0)
    product: str | None = None
    product_sub: str | None = Field(None, alias='productSub')
    max_touch_points: int | None = Field(None, alias='maxTouchPoints', ge=0)
    cookie_enabled: bool | None = Field(None, alias='cookieEnabled')
    global_privacy_control: bool | None = Field(None, alias='globalPrivacyControl')
    build_id: str | None = Field(None, alias='buildID')
    on_line: bool | None = Field(None, alias='onLine')


class ColorGamut(Enum):
    srgb = 'srgb'
    p3 = 'p3'
    rec2020 = 'rec2020'


class DynamicRange(Enum):
    standard = 'standard'
    high = 'high'


class VideoDynamicRange(Enum):
    standard = 'standard'
    high = 'high'


class ScreenProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    avail_height: int | None = Field(None, alias='availHeight', ge=0)
    avail_width: int | None = Field(None, alias='availWidth', ge=0)
    avail_top: int | None = Field(None, alias='availTop', ge=0)
    avail_left: int | None = Field(None, alias='availLeft', ge=0)
    height: int | None = Field(None, ge=0)
    width: int | None = Field(None, ge=0)
    color_depth: int | None = Field(None, alias='colorDepth', ge=0)
    pixel_depth: int | None = Field(None, alias='pixelDepth', ge=0)
    color_gamut: ColorGamut | None = Field(None, alias='colorGamut')
    dynamic_range: DynamicRange | None = Field(None, alias='dynamicRange')
    video_dynamic_range: VideoDynamicRange | None = Field(
        None, alias='videoDynamicRange'
    )
    page_x_offset: float | None = Field(None, alias='pageXOffset')
    page_y_offset: float | None = Field(None, alias='pageYOffset')


class HistoryProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    length: int | None = Field(None, ge=0)


class DocumentBodyProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client_width: int | None = Field(None, alias='clientWidth', ge=0)
    client_height: int | None = Field(None, alias='clientHeight', ge=0)
    client_top: int | None = Field(None, alias='clientTop')
    client_left: int | None = Field(None, alias='clientLeft')


class HeaderProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_agent: str | None = Field(None, alias='User-Agent')
    accept_language: str | None = Field(None, alias='Accept-Language')
    accept_encoding: str | None = Field(None, alias='Accept-Encoding')


class WebRtcProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ipv4: str | None = None
    ipv6: str | None = None
    localipv4: str | None = None
    localipv6: str | None = None


class BatteryProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    charging: bool | None = None
    charging_time: float | None = Field(None, alias='chargingTime', ge=0.0)
    discharging_time: float | None = Field(None, alias='dischargingTime', ge=0.0)
    level: float | None = Field(None, ge=0.0)


class FontsProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    families: list[str] | None = None
    spacing_seed: int | None = Field(None, alias='spacingSeed', ge=0)


class AudioProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    seed: int | None = Field(None, ge=0)


class GeolocationProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    latitude: float | None = Field(None, ge=-90.0, le=90.0)
    longitude: float | None = Field(None, ge=-180.0, le=180.0)
    accuracy: float | None = Field(None, ge=0.0)


class LocaleProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    language: str | None = None
    region: str | None = None
    script: str | None = None
    all: str | None = None


class HumanizeProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enabled: bool | None = None
    max_time: float | None = Field(None, alias='maxTime', ge=0.0)
    min_time: float | None = Field(None, alias='minTime', ge=0.0)


class AudioContextProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sample_rate: int | None = Field(None, alias='sampleRate', ge=0)
    output_latency: float | None = Field(None, alias='outputLatency', ge=0.0)
    max_channel_count: int | None = Field(None, alias='maxChannelCount', ge=0)


class SpeechVoice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    is_local_service: bool = Field(..., alias='isLocalService')
    is_default: bool = Field(..., alias='isDefault')
    voice_uri: str = Field(..., alias='voiceUri')
    name: str
    lang: str


class MediaDevicesProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    micros: int | None = Field(None, ge=0)
    webcams: int | None = Field(None, ge=0)
    speakers: int | None = Field(None, ge=0)
    enabled: bool | None = None


class WindowProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scroll_min_x: int | None = Field(None, alias='scrollMinX')
    scroll_min_y: int | None = Field(None, alias='scrollMinY')
    scroll_max_x: int | None = Field(None, alias='scrollMaxX')
    scroll_max_y: int | None = Field(None, alias='scrollMaxY')
    outer_height: int | None = Field(None, alias='outerHeight', ge=0)
    outer_width: int | None = Field(None, alias='outerWidth', ge=0)
    inner_height: int | None = Field(None, alias='innerHeight', ge=0)
    inner_width: int | None = Field(None, alias='innerWidth', ge=0)
    screen_x: int | None = Field(None, alias='screenX')
    screen_y: int | None = Field(None, alias='screenY')
    history: HistoryProfile | None = None
    device_pixel_ratio: float | None = Field(None, alias='devicePixelRatio', gt=0.0)


class DocumentProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: DocumentBodyProfile | None = None


class VoicesProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[str | SpeechVoice] | None = None
    block_if_not_defined: bool | None = Field(None, alias='blockIfNotDefined')
    fake_completion: bool | None = Field(None, alias='fakeCompletion')
    fake_completion_chars_per_second: float | None = Field(
        None, alias='fakeCompletionCharsPerSecond', gt=0.0
    )


class RotundaProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    navigator: NavigatorProfile | None = None
    screen: ScreenProfile | None = None
    window: WindowProfile | None = None
    document: DocumentProfile | None = None
    headers: HeaderProfile | None = None
    webrtc: WebRtcProfile | None = None
    pdf_viewer_enabled: bool | None = Field(None, alias='pdfViewerEnabled')
    battery: BatteryProfile | None = None
    fonts: FontsProfile | None = None
    audio: AudioProfile | None = None
    geolocation: GeolocationProfile | None = None
    timezone: str | None = None
    locale: LocaleProfile | None = None
    humanize: HumanizeProfile | None = None
    showcursor: bool | None = None
    audio_context: AudioContextProfile | None = Field(None, alias='audioContext')
    voices: VoicesProfile | None = None
    media_devices: MediaDevicesProfile | None = Field(None, alias='mediaDevices')
    allow_main_world: bool | None = Field(None, alias='allowMainWorld')
    force_scope_access: bool | None = Field(None, alias='forceScopeAccess')
    disable_theming: bool | None = Field(None, alias='disableTheming')
    memorysaver: bool | None = None
    addons: list[str] | None = None
    certificate_paths: list[str] | None = Field(None, alias='certificatePaths')
    certificates: list[str] | None = None
    debug: bool | None = None
