import json as _json
import urllib.request
from typing import Any, Literal, overload
from urllib.parse import urlparse

from browserforge.fingerprints import Fingerprint
from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)

from camoufox.virtdisplay import VirtualDisplay

from .exceptions import InvalidProxy
from .fingerprints import generate_context_fingerprint
from .utils import launch_options, sync_attach_vd


class Camoufox(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, **launch_options):
        super().__init__()
        self.launch_options = launch_options
        self.browser: Browser | BrowserContext | None = None

    def __enter__(self) -> Any:
        super().__enter__()
        try:
            self.browser = NewBrowser(self._playwright, **self.launch_options)
        except InvalidProxy as e:
            super().__exit__(InvalidProxy, e, None)
            raise
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: dict[str, Any] | None = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: dict[str, Any] | None = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


def NewBrowser(
    playwright: Playwright,
    *,
    headless: bool | Literal['virtual'] | None = None,
    from_options: dict[str, Any] | None = None,
    persistent_context: bool = False,
    debug: bool | None = None,
    **kwargs,
) -> Browser | BrowserContext:
    """
    Launches a new browser instance for Camoufox given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    if not from_options:
        from_options = launch_options(headless=headless, debug=debug, **kwargs)
    assert from_options is not None

    # Persistent context
    if persistent_context:
        context = playwright.firefox.launch_persistent_context("", **from_options)
        return sync_attach_vd(context, virtual_display)

    # Browser
    browser = playwright.firefox.launch(**from_options)
    return sync_attach_vd(browser, virtual_display)


def _proxy_url_with_creds(proxy: dict[str, str]) -> str:
    """Builds a proxy URL string with embedded credentials."""
    parsed = urlparse(proxy.get("server", ""))
    user = proxy.get("username", "")
    pwd = proxy.get("password", "")
    if user and pwd:
        return f"{parsed.scheme}://{user}:{pwd}@{parsed.netloc}"
    return proxy.get("server", "")


def _resolve_proxy_geo(proxy: dict[str, str]) -> dict[str, str | None]:
    """Queries ip-api.com through the proxy for the exit IP and timezone."""
    proxy_url = _proxy_url_with_creds(proxy)
    handler = urllib.request.ProxyHandler({"http": proxy_url, "https": proxy_url})
    opener = urllib.request.build_opener(handler)
    try:
        with opener.open("http://ip-api.com/json?fields=query,timezone", timeout=10) as resp:
            data = _json.loads(resp.read())
            return {"ip": data.get("query") or None, "timezone": data.get("timezone") or None}
    except Exception:
        return {"ip": None, "timezone": None}


def NewContext(
    browser: Browser,
    *,
    fingerprint: Fingerprint | None = None,
    preset: dict[str, Any] | None = None,
    os: str | None = None,
    ff_version: str | None = None,
    webrtc_ip: str | None = None,
    proxy: dict[str, str] | None = None,
    geolocation: dict[str, float] | None = None,
    debug: bool | None = None,
    **context_kwargs: Any,
) -> BrowserContext:
    """
    Creates a new browser context with a unique fingerprint identity.

    Each context gets its own host-compatible Firefox fingerprint identity.
    BrowserForge supplies the navigator/screen skeleton, while fonts and
    voices are sampled directly from the real macOS host inventory. GPU-facing
    values stay real. All values are applied via addInitScript so they
    self-destruct before page scripts can detect them.

    Parameters:
        browser: A Browser instance from NewBrowser or Camoufox.
        fingerprint: A BrowserForge fingerprint to compile directly. Use this
            when you need the browser launch and the page context to share the
            same navigator and geometry skeleton.
        preset: A specific fingerprint preset dict to compile. If None,
            BrowserForge generates the fingerprint skeleton.
        os: Target OS for BrowserForge/preset sampling. The default
            host-compatible path currently supports only the real macOS host OS.
        ff_version: Firefox version string for UA patching.
        webrtc_ip: IPv4 address to spoof for WebRTC ICE candidates.
        proxy: Per-context proxy (Playwright format: {"server": "...", "username": "...", "password": "..."}).
        geolocation: Per-context geolocation ({"latitude": float, "longitude": float}).
        debug: When True, print fingerprint generation diagnostics.
        **context_kwargs: Additional Playwright new_context() options.
    """
    # Auto-derive WebRTC IP and timezone from proxy's exit IP when not explicitly provided
    if proxy and (not webrtc_ip or "timezone_id" not in context_kwargs):
        geo = _resolve_proxy_geo(proxy)
        if not webrtc_ip:
            webrtc_ip = geo["ip"]
        if "timezone_id" not in context_kwargs and geo["timezone"]:
            context_kwargs["timezone_id"] = geo["timezone"]

    fp = generate_context_fingerprint(
        fingerprint=fingerprint,
        preset=preset,
        os=os,
        ff_version=ff_version,
        webrtc_ip=webrtc_ip,
        debug=bool(debug),
    )

    # Merge generated context options with user overrides (user wins)
    opts: dict[str, Any] = {**fp['context_options'], **context_kwargs}
    if proxy:
        opts['proxy'] = proxy
    if geolocation:
        opts['geolocation'] = geolocation
        opts.setdefault('permissions', ['geolocation'])

    context = browser.new_context(**opts)
    context.add_init_script(fp['init_script'])
    return context
