# generated by datamodel-codegen:
#   filename:  rotunda-ml-data-capture.openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(Enum):
    session_started = 'session_started'


class SessionStartedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_started']
    offset_ms: int | None = Field(None, alias='offsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)


class Type1(Enum):
    session_stopped = 'session_stopped'


class SessionStoppedEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session_stopped']
    offset_ms: int | None = Field(None, alias='offsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)


class Type2(Enum):
    mouse_move = 'mouse_move'


class Type3(Enum):
    mouse_click = 'mouse_click'


class Type4(Enum):
    keyboard = 'keyboard'


class Type5(Enum):
    focused_element = 'focused_element'


class FocusedElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bundle_id: str | None = Field(None, alias='bundleID')
    process_id: int | None = Field(None, alias='processID')
    accessibility_id: str | None = Field(None, alias='accessibilityID')
    dom_id: str | None = Field(None, alias='domID')
    role: str | None = None
    subrole: str | None = None
    is_password: bool | None = Field(None, alias='isPassword')
    value_redacted: bool | None = Field(None, alias='valueRedacted')
    value: str | None = None


class MouseButton(Enum):
    left = 'left'
    middle = 'middle'
    center = 'center'
    right = 'right'
    other = 'other'


class MouseButtonOrNone(Enum):
    none = 'none'
    left = 'left'
    middle = 'middle'
    center = 'center'
    right = 'right'
    other = 'other'


class MouseMoveEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['mouse_move']
    offset_ms: int = Field(..., alias='offsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)
    x: float = Field(..., description='Absolute pointer x coordinate in screen pixels.')
    y: float = Field(..., description='Absolute pointer y coordinate in screen pixels.')
    delta_x: float | None = Field(
        None,
        alias='deltaX',
        description='Pointer x delta from the previous mouse event.',
    )
    delta_y: float | None = Field(
        None,
        alias='deltaY',
        description='Pointer y delta from the previous mouse event.',
    )
    drag_button: MouseButtonOrNone | None = Field(None, alias='dragButton')


class MouseClickEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['mouse_click']
    offset_ms: int = Field(..., alias='offsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)
    x: float = Field(..., description='Absolute click x coordinate in screen pixels.')
    y: float = Field(..., description='Absolute click y coordinate in screen pixels.')
    button: MouseButton | None = None
    click_count: int | None = Field(None, alias='clickCount', ge=1)


class KeyboardEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['keyboard']
    offset_ms: int = Field(..., alias='offsetMs', ge=0)
    trigger_offset_ms: int | None = Field(None, alias='triggerOffsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)
    focused_element: FocusedElement = Field(..., alias='focusedElement')


class FocusedElementEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['focused_element']
    offset_ms: int = Field(..., alias='offsetMs', ge=0)
    trigger_offset_ms: int | None = Field(None, alias='triggerOffsetMs', ge=0)
    screen_width: int | None = Field(None, alias='screenWidth', ge=0)
    screen_height: int | None = Field(None, alias='screenHeight', ge=0)
    focused_element: FocusedElement = Field(..., alias='focusedElement')


class CaptureEvent(
    RootModel[
        SessionStartedEvent
        | SessionStoppedEvent
        | MouseMoveEvent
        | MouseClickEvent
        | KeyboardEvent
        | FocusedElementEvent
    ]
):
    root: (
        SessionStartedEvent
        | SessionStoppedEvent
        | MouseMoveEvent
        | MouseClickEvent
        | KeyboardEvent
        | FocusedElementEvent
    ) = Field(
        ...,
        description='One line from a recorder NDJSON data capture file.',
        discriminator='type',
    )
